<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Propel\Bundle\PropelBundle\PropelBundle::class => ['all' => true],
    Creonit\PropelSchemaConverterBundle\CreonitPropelSchemaConverterBundle::class => ['all' => true],
    Creonit\AdminBundle\CreonitAdminBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Cocur\Slugify\Bridge\Symfony\CocurSlugifyBundle::class => ['all' => true],
    Gregwar\ImageBundle\GregwarImageBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Creonit\ContentBundle\CreonitContentBundle::class => ['all' => true],
    Creonit\PageBundle\CreonitPageBundle::class => ['all' => true],
    Creonit\MediaBundle\CreonitMediaBundle::class => ['all' => true],
    Creonit\StorageBundle\CreonitStorageBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Creonit\NuxtBundle\CreonitNuxtBundle::class => ['all' => true],
    Creonit\RestBundle\CreonitRestBundle::class => ['all' => true],
    Creonit\VerificationCodeBundle\CreonitVerificationCodeBundle::class => ['all' => true],
    Creonit\MailingBundle\CreonitMailingBundle::class => ['all' => true],
    Symfony\Bundle\MercureBundle\MercureBundle::class => ['all' => true],
];
