creonit_verification_code:
    generator:
        config:
            length: 4
    scopes:
        phone:
            key_pattern: '/^\+\d{1,3} *(\(\d{3,4}\)|\d{3,4})([ -]*\d){6,7}$/'
            max_age: 180
            attempt_time: 120

        scope_name:
            max_age: 120
