monolog:
    channels:
        - mercury
        - sms
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        mercury:
            type: stream
            path: "%kernel.logs_dir%/mercury.log"
            channels: ['mercury']
        sms:
            type: stream
            path: "%kernel.logs_dir%/sms.log"
            channels: ['sms']
